### ISSUE TITLE
Updating to Bootstrap 3

### ISSUE THREAD

**Issue by gbaudoin** [zohararad/wysihtml5n#4]
The current version is made for Bootstrap 2.

I'm trying to have it working with bootstrap 3 - so far, only the modal of insertImage and insertLink window seems to be of trouble.

**Comment by cbielich** [comment]
FYI I edited your project and the changes are now Bootstrap 3 compatible. Also a suggestion on usage it might be beneficial to let users know if they are using ajax to upload the BASE64 image they need to do it the right way like this

data: {image: image},

and not like the old school way, it will break

data: 'image='+image+

**Comment by zohararad** [comment]
Thanks a lot! Is there a PR with this change?

**Comment by cbielich** [comment]
lol I don't do GitHub much, what is PR?

**Comment by gbaudoin** [comment]
If you want to create a pull request between the patch-3 branch of your fork and zoharad's base, go to 
https://github.com/zohararad/wysihtml5n/compare/master...cbielich:patch-3

**Comment by cbielich** [comment]
Ok its done, you should see it

**Comment by zohararad** [comment]
ok to close this one?

**Comment by gbaudoin** [comment]
Closing ! #6  Thanks @cbielich for the pull and @zohararad for the merge !
